### ISSUE TITLE
Production permissions fails to start tomcat 8.5.45 service on RHEL7

### ISSUE THREAD

**Issue by Sam-Hall** [zaxos/tomcat-ansible-role#11]
Group execute permission is missing from bin/*.sh, so tomcat user can't run startup.sh or shutdown.sh. Here's the error in the playbook...
`RUNNING HANDLER [zaxos.tomcat-ansible-role : restart tomcat] *********************************
fatal: [prod_host]: FAILED! => {"changed": false, "msg": "Unable to start service tomcat: Job for tomcat.service failed because the control process exited with error code. See \"systemctl status tomcat.service\" and \"journalctl -xe\" for details.\n"}`

and here is the other error...
`Aug 26 00:03:52 prod_host systemd[23492]: Failed at step EXEC spawning /path/to/tomcat/bin/startup.sh: Permission denied
-- Subject: Process /path/to/tomcat/bin/startup.sh could not be executed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The process /path/to/tomcat/bin/startup.sh could not be executed and failed.
-- 
-- The error number returned by this process is 13.`

**Comment by Sam-Hall** [comment]
The bug is at the end of set-production-permissions.yml. "0740" should be "0750" end of line 50.

**Comment by zaxos** [comment]
Fixed!
