### ISSUE TITLE
EL8 support ?

### ISSUE THREAD

**Issue by ggambini** [zaxos/tomcat-ansible-role#20]
Hello,

Did you plan to support Red Hat EL8 soon ?

Thank you, Gilian.

**Comment by zaxos** [comment]
Hello,

I verified CentOS/RHEL 8 support, no changes were necessary.

Thank you

**Comment by ggambini** [comment]
Good news :)

Have a nice day, Gilian.

**Comment by ggambini** [comment]
Successfully tested on EL8, thank you.
