### ISSUE TITLE
Role forces me to include all plays/tasks as root (i.e. become:true)

### ISSUE THREAD

**Issue by morgangraphics** [zaxos/tomcat-ansible-role#5]
Typically you'd only want to include the `become: true` where you need it making it dependent on the the task. The idea following the [principal of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) to prevent everything running as root.

You may want to evaluate which tasks actually need to be run as root and update the role accordingly.  At the very least you should mention that `become: true` is needed to run the role in the documentation.

**Comment by zaxos** [comment]
You are right, now `become: true` is mentioned in example playbook.
