### ISSUE TITLE
Request: Manage own settings.xml file

### ISSUE THREAD

**Issue by morgangraphics** [zaxos/tomcat-ansible-role#7]
I appreciate the role setting/managing some sensible defaults. However, I'd like the option to use my own settings.xml file rather than using the ansible blockinfile to inject my stuff into your template. 

perhaps it's just another variable like `settings_file_path` where is could be a straight up copy or interpolated through jinja.

**Comment by zaxos** [comment]
Added template variables to enable usage of custom templates for server.xml, users.xml, systemd service file, etc.
